<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SiteStructure\Module'                          => __DIR__ . '/Module.php',
    'SiteStructure\Controller\IndexController'      => __DIR__ . '/src/SiteStructure/Controller/IndexController.php',
);