<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tools\Module'                          => __DIR__ . '/Module.php',
    'Tools\Controller\IndexController'      => __DIR__ . '/src/Tools/Controller/IndexController.php',
);