<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Templates\Module'                        => __DIR__ . '/Module.php',
    'Templates\Controller\IndexController' => __DIR__ . '/src/Templates/Controller/IndexController.php',
);